export type BoatStatus = "in-service" | "needs-maintenance" | "out-of-service" | "dry-dock";

export interface Boat {
  id: string;
  name: string;
  code: string;
  category: string;
  slip: number;
  dock: "A" | "B";
  dockSide: "left" | "right";
  dockRow: number; // 1 = nearest shore, higher = toward open water
  status: BoatStatus;
  hp: number;
  capacity: number;
  make: string;
  notes: string;
  canPullTube: boolean;
  canPullDouble: boolean;
  canPullKneeboard: boolean;
  hasWaterMat: boolean;
  lastCleaned: string;
  lastCleanedBy: string;
  cleaningSignedOffBy: string;
  lastOut: string;
  nextOut: string;
  morningCheckDone: boolean;
  morningCheckBy: string;
  outstandingTasks: string[];
  maintenanceNote: string;
}

// Dock A — right side: slips 1–7 + Tiki (rows 1–8 from shore)
// Dock A — left side: slips 8–20 (rows 1–13 from shore)
// Dock B — right side: slips 22–36 (rows 1–15 from shore)
// Dock B — left side: customer slips (greyed out, rows 1–15)

export const boats: Boat[] = [
  // ── DOCK A · RIGHT (shore → water) ──────────────────────────────────────
  {
    id: "cobia",
    name: "Cobia", code: "",
    category: "Utility",
    slip: 1, dock: "A", dockSide: "right", dockRow: 1,
    status: "in-service",
    hp: 115, capacity: 4, make: "Cobia",
    notes: "Utility / work boat",
    canPullTube: false, canPullDouble: false, canPullKneeboard: false, hasWaterMat: false,
    lastCleaned: "Apr 19, 9:00am", lastCleanedBy: "Tyler", cleaningSignedOffBy: "Sam",
    lastOut: "Apr 19, 3:30pm", nextOut: "Apr 20, 8:00am",
    morningCheckDone: true, morningCheckBy: "Tyler",
    outstandingTasks: [],
    maintenanceNote: "",
  },
  {
    id: "pp1-tortola",
    name: "Tortola", code: "PP1",
    category: "Premium Pontoon",
    slip: 2, dock: "A", dockSide: "right", dockRow: 2,
    status: "in-service",
    hp: 150, capacity: 10, make: "Bennington",
    notes: "2021–2024 model, tritoon. Single + double tube, kneeboard, water mat.",
    canPullTube: true, canPullDouble: true, canPullKneeboard: true, hasWaterMat: true,
    lastCleaned: "Apr 19, 10:15am", lastCleanedBy: "Kenny", cleaningSignedOffBy: "Sam",
    lastOut: "Apr 19, 11:00am", nextOut: "Apr 20, 9:00am",
    morningCheckDone: true, morningCheckBy: "Kenny",
    outstandingTasks: [],
    maintenanceNote: "",
  },
  {
    id: "pp2-jamaica",
    name: "Jamaica", code: "PP2",
    category: "Premium Pontoon",
    slip: 3, dock: "A", dockSide: "right", dockRow: 3,
    status: "in-service",
    hp: 150, capacity: 10, make: "Bennington",
    notes: "2021–2024 model, tritoon.",
    canPullTube: true, canPullDouble: true, canPullKneeboard: true, hasWaterMat: true,
    lastCleaned: "Apr 19, 10:30am", lastCleanedBy: "Zach", cleaningSignedOffBy: "Sam",
    lastOut: "Apr 19, 2:00pm", nextOut: "Apr 20, 10:00am",
    morningCheckDone: true, morningCheckBy: "Zach",
    outstandingTasks: [],
    maintenanceNote: "",
  },
  {
    id: "pp3-bermuda",
    name: "Bermuda", code: "PP3",
    category: "Premium Pontoon",
    slip: 4, dock: "A", dockSide: "right", dockRow: 4,
    status: "out-of-service",
    hp: 150, capacity: 10, make: "Bennington",
    notes: "2021–2024 model, tritoon.",
    canPullTube: true, canPullDouble: true, canPullKneeboard: true, hasWaterMat: true,
    lastCleaned: "Apr 17, 4:00pm", lastCleanedBy: "Tyler", cleaningSignedOffBy: "Dave",
    lastOut: "Apr 17, 3:30pm", nextOut: "TBD",
    morningCheckDone: false, morningCheckBy: "",
    outstandingTasks: [
      "Send service request to Matt if not already done",
      "Follow up with Matt — it's been 4 days, ask for a status check",
      "Check last rental and reach out to customer if needed",
    ],
    maintenanceNote: "Engine overheating reported Apr 17. Out of service. Parts ordered, ETA unknown.",
  },
  {
    id: "pp4-curacao",
    name: "Curacao", code: "PP4",
    category: "Premium Pontoon",
    slip: 5, dock: "A", dockSide: "right", dockRow: 5,
    status: "in-service",
    hp: 150, capacity: 10, make: "Bennington",
    notes: "2021–2024 model, tritoon.",
    canPullTube: true, canPullDouble: true, canPullKneeboard: true, hasWaterMat: true,
    lastCleaned: "Apr 19, 11:00am", lastCleanedBy: "Parker", cleaningSignedOffBy: "Sam",
    lastOut: "Apr 19, 1:00pm", nextOut: "Apr 20, 11:00am",
    morningCheckDone: true, morningCheckBy: "Parker",
    outstandingTasks: ["Order replacement bow cover"],
    maintenanceNote: "",
  },
  {
    id: "pp5-belize",
    name: "Belize", code: "PP5",
    category: "Premium Pontoon",
    slip: 6, dock: "A", dockSide: "right", dockRow: 6,
    status: "needs-maintenance",
    hp: 150, capacity: 10, make: "Bennington",
    notes: "2021–2024 model, tritoon.",
    canPullTube: true, canPullDouble: true, canPullKneeboard: true, hasWaterMat: true,
    lastCleaned: "Apr 19, 11:30am", lastCleanedBy: "Kenny", cleaningSignedOffBy: "Sam",
    lastOut: "Apr 19, 9:00am", nextOut: "Apr 20, 9:00am",
    morningCheckDone: true, morningCheckBy: "Kenny",
    outstandingTasks: [
      "Go take a better photo of the prop — current one is blurry",
      "Talk to Zach about what happened on the rental",
      "Lake test before putting back in rotation — manager sign-off required",
      "Send service request to Matt if prop needs replacement",
    ],
    maintenanceNote: "Prop damage reported after last rental. Still operational but needs inspection.",
  },
  {
    id: "jcb-right",
    name: "JCB", code: "JCB",
    category: "Jet Car Boat",
    slip: 7, dock: "A", dockSide: "right", dockRow: 7,
    status: "in-service",
    hp: 255, capacity: 4, make: "Hydra-Sports",
    notes: "Jet-powered, 4 passengers max. No tube pulling.",
    canPullTube: false, canPullDouble: false, canPullKneeboard: false, hasWaterMat: false,
    lastCleaned: "Apr 19, 8:00am", lastCleanedBy: "Nate", cleaningSignedOffBy: "Sam",
    lastOut: "Apr 19, 10:00am", nextOut: "Apr 20, 10:00am",
    morningCheckDone: true, morningCheckBy: "Nate",
    outstandingTasks: [],
    maintenanceNote: "",
  },
  {
    id: "tiki-boat",
    name: "Tiki Boat", code: "TIKI",
    category: "Tiki Charter",
    slip: 0, dock: "A", dockSide: "right", dockRow: 8,
    status: "in-service",
    hp: 90, capacity: 14, make: "Custom",
    notes: "Public/private charter. Bar onboard.",
    canPullTube: false, canPullDouble: false, canPullKneeboard: false, hasWaterMat: false,
    lastCleaned: "Apr 19, 7:30am", lastCleanedBy: "Tyler", cleaningSignedOffBy: "Dave",
    lastOut: "Apr 19, 5:00pm", nextOut: "Apr 20, 1:00pm",
    morningCheckDone: true, morningCheckBy: "Tyler",
    outstandingTasks: ["Restock bar supplies before Apr 20 charter"],
    maintenanceNote: "",
  },

  // ── DOCK A · LEFT (shore → water) ────────────────────────────────────────
  {
    id: "captree-1",
    name: "Captree 1", code: "",
    category: "Utility",
    slip: 8, dock: "A", dockSide: "left", dockRow: 1,
    status: "in-service",
    hp: 115, capacity: 4, make: "Captree",
    notes: "Chase / utility boat.",
    canPullTube: false, canPullDouble: false, canPullKneeboard: false, hasWaterMat: false,
    lastCleaned: "Apr 19, 9:00am", lastCleanedBy: "Nate", cleaningSignedOffBy: "Sam",
    lastOut: "Apr 19, 2:00pm", nextOut: "Apr 20, 8:00am",
    morningCheckDone: true, morningCheckBy: "Nate",
    outstandingTasks: [],
    maintenanceNote: "",
  },
  {
    id: "pp6-bahamas",
    name: "Bahamas", code: "PP6",
    category: "Premium Pontoon",
    slip: 9, dock: "A", dockSide: "left", dockRow: 2,
    status: "in-service",
    hp: 150, capacity: 10, make: "Bennington",
    notes: "2021–2024 model, tritoon.",
    canPullTube: true, canPullDouble: true, canPullKneeboard: true, hasWaterMat: true,
    lastCleaned: "Apr 19, 12:00pm", lastCleanedBy: "Zach", cleaningSignedOffBy: "Sam",
    lastOut: "Apr 19, 11:00am", nextOut: "Apr 20, 8:30am",
    morningCheckDone: true, morningCheckBy: "Zach",
    outstandingTasks: [],
    maintenanceNote: "",
  },
  {
    id: "pp7-barbados",
    name: "Barbados", code: "PP7",
    category: "Premium Pontoon",
    slip: 10, dock: "A", dockSide: "left", dockRow: 3,
    status: "needs-maintenance",
    hp: 150, capacity: 10, make: "Bennington",
    notes: "2021–2024 model, tritoon.",
    canPullTube: true, canPullDouble: true, canPullKneeboard: true, hasWaterMat: true,
    lastCleaned: "Apr 18, 4:30pm", lastCleanedBy: "Kenny", cleaningSignedOffBy: "Sam",
    lastOut: "Apr 19, 10:00am", nextOut: "Apr 20, 9:00am",
    morningCheckDone: false, morningCheckBy: "",
    outstandingTasks: [
      "Talk to Kenny — get more detail on what he felt",
      "Manager: take it out for a lake test before deciding",
      "Tell Dave before sending to service — he may know what it is",
    ],
    maintenanceNote: "Steering resistance reported by last captain. Still operational — flag for Dave.",
  },
  {
    id: "pp8-premiere",
    name: "Premiere", code: "PP8",
    category: "Premium Pontoon",
    slip: 11, dock: "A", dockSide: "left", dockRow: 4,
    status: "in-service",
    hp: 150, capacity: 12, make: "Premier",
    notes: "Holds 12 (not Bennington). Exception to standard 10-person cap — not advertised.",
    canPullTube: true, canPullDouble: true, canPullKneeboard: true, hasWaterMat: true,
    lastCleaned: "Apr 19, 1:00pm", lastCleanedBy: "Parker", cleaningSignedOffBy: "Dave",
    lastOut: "Apr 19, 2:00pm", nextOut: "Apr 20, 10:00am",
    morningCheckDone: true, morningCheckBy: "Parker",
    outstandingTasks: [],
    maintenanceNote: "",
  },
  {
    id: "pp9-allora",
    name: "Allora", code: "PP9",
    category: "Premium Pontoon",
    slip: 12, dock: "A", dockSide: "left", dockRow: 5,
    status: "in-service",
    hp: 150, capacity: 10, make: "Bennington",
    notes: "2021–2024 model, tritoon.",
    canPullTube: true, canPullDouble: true, canPullKneeboard: true, hasWaterMat: true,
    lastCleaned: "Apr 19, 11:45am", lastCleanedBy: "Tyler", cleaningSignedOffBy: "Sam",
    lastOut: "Apr 19, 12:00pm", nextOut: "Apr 20, 11:00am",
    morningCheckDone: true, morningCheckBy: "Tyler",
    outstandingTasks: [],
    maintenanceNote: "",
  },
  {
    id: "pp10-belle",
    name: "Belle", code: "PP10",
    category: "Premium Pontoon",
    slip: 13, dock: "A", dockSide: "left", dockRow: 6,
    status: "in-service",
    hp: 150, capacity: 10, make: "Bennington",
    notes: "2021–2024 model, tritoon.",
    canPullTube: true, canPullDouble: true, canPullKneeboard: true, hasWaterMat: true,
    lastCleaned: "Apr 19, 10:00am", lastCleanedBy: "Nate", cleaningSignedOffBy: "Sam",
    lastOut: "Apr 19, 9:00am", nextOut: "Apr 20, 9:00am",
    morningCheckDone: true, morningCheckBy: "Nate",
    outstandingTasks: [],
    maintenanceNote: "",
  },
  {
    id: "jcb-left",
    name: "JCB", code: "JCB",
    category: "Jet Car Boat",
    slip: 14, dock: "A", dockSide: "left", dockRow: 7,
    status: "in-service",
    hp: 255, capacity: 4, make: "Hydra-Sports",
    notes: "Jet-powered, 4 passengers max.",
    canPullTube: false, canPullDouble: false, canPullKneeboard: false, hasWaterMat: false,
    lastCleaned: "Apr 19, 8:00am", lastCleanedBy: "Zach", cleaningSignedOffBy: "Sam",
    lastOut: "Apr 19, 3:00pm", nextOut: "Apr 20, 11:00am",
    morningCheckDone: true, morningCheckBy: "Zach",
    outstandingTasks: [],
    maintenanceNote: "",
  },
  {
    id: "s1-grand-turk",
    name: "Grand Turk", code: "S1",
    category: "Standard Slide Pontoon",
    slip: 15, dock: "A", dockSide: "left", dockRow: 8,
    status: "dry-dock",
    hp: 175, capacity: 12, make: "Godfrey",
    notes: "2023 model, tritoon. Double decker slide + water slide. Single tube only.",
    canPullTube: true, canPullDouble: false, canPullKneeboard: false, hasWaterMat: true,
    lastCleaned: "Apr 15, 11:00am", lastCleanedBy: "Tyler", cleaningSignedOffBy: "Dave",
    lastOut: "Nov 3, 2025", nextOut: "May 1, 2026 (season open)",
    morningCheckDone: false, morningCheckBy: "",
    outstandingTasks: ["Pre-season inspection Apr 25", "Check slide mechanism"],
    maintenanceNote: "In dry dock — pre-season prep. Launch target May 1.",
  },
  {
    id: "s2-cozumel",
    name: "Cozumel", code: "S2",
    category: "Standard Slide Pontoon",
    slip: 16, dock: "A", dockSide: "left", dockRow: 9,
    status: "dry-dock",
    hp: 175, capacity: 12, make: "Godfrey",
    notes: "2023 model, tritoon. Double decker slide.",
    canPullTube: true, canPullDouble: false, canPullKneeboard: false, hasWaterMat: true,
    lastCleaned: "Apr 15, 11:00am", lastCleanedBy: "Kenny", cleaningSignedOffBy: "Dave",
    lastOut: "Nov 3, 2025", nextOut: "May 1, 2026 (season open)",
    morningCheckDone: false, morningCheckBy: "",
    outstandingTasks: ["Pre-season inspection Apr 25"],
    maintenanceNote: "In dry dock — pre-season prep.",
  },
  {
    id: "s3-grand-exuma",
    name: "Grand Exuma", code: "S3",
    category: "Standard Slide Pontoon",
    slip: 17, dock: "A", dockSide: "left", dockRow: 10,
    status: "dry-dock",
    hp: 175, capacity: 12, make: "Godfrey",
    notes: "2023 model, tritoon. Double decker slide.",
    canPullTube: true, canPullDouble: false, canPullKneeboard: false, hasWaterMat: true,
    lastCleaned: "Apr 15, 11:00am", lastCleanedBy: "Parker", cleaningSignedOffBy: "Dave",
    lastOut: "Nov 3, 2025", nextOut: "May 1, 2026 (season open)",
    morningCheckDone: false, morningCheckBy: "",
    outstandingTasks: ["Pre-season inspection Apr 25", "Replace water mat before launch"],
    maintenanceNote: "In dry dock. Water mat needs replacement.",
  },
  {
    id: "s4-port-royale",
    name: "Port Royale", code: "S4",
    category: "Standard Slide Pontoon",
    slip: 18, dock: "A", dockSide: "left", dockRow: 11,
    status: "dry-dock",
    hp: 175, capacity: 12, make: "Bennington",
    notes: "2023 model, Bennington tritoon. Double decker slide.",
    canPullTube: true, canPullDouble: false, canPullKneeboard: false, hasWaterMat: true,
    lastCleaned: "Apr 15, 11:00am", lastCleanedBy: "Nate", cleaningSignedOffBy: "Dave",
    lastOut: "Nov 3, 2025", nextOut: "May 1, 2026 (season open)",
    morningCheckDone: false, morningCheckBy: "",
    outstandingTasks: ["Pre-season inspection Apr 25"],
    maintenanceNote: "In dry dock — pre-season prep.",
  },
  {
    id: "psp1-breaksea",
    name: "Breaksea", code: "PSP1",
    category: "Premium Slide Pontoon",
    slip: 19, dock: "A", dockSide: "left", dockRow: 12,
    status: "dry-dock",
    hp: 250, capacity: 14, make: "Bennington",
    notes: "Brand new 2025 vessel. 250HP tritoon. Double decker slide + water slide. Single tube only.",
    canPullTube: true, canPullDouble: false, canPullKneeboard: false, hasWaterMat: true,
    lastCleaned: "Apr 16, 10:00am", lastCleanedBy: "Tyler", cleaningSignedOffBy: "Dave",
    lastOut: "N/A — new 2025", nextOut: "May 1, 2026 (season open)",
    morningCheckDone: false, morningCheckBy: "",
    outstandingTasks: [
      "Final pre-season detail Apr 28",
      "Confirm registration docs with Sue",
    ],
    maintenanceNote: "Brand new 2025. Final pre-season setup underway.",
  },
  {
    id: "psp2-beaumont",
    name: "Beaumont", code: "PSP2",
    category: "Premium Slide Pontoon",
    slip: 20, dock: "A", dockSide: "left", dockRow: 13,
    status: "dry-dock",
    hp: 250, capacity: 12, make: "Bennington",
    notes: "Brand new 2025 vessel. 250HP tritoon. Double decker slide.",
    canPullTube: true, canPullDouble: false, canPullKneeboard: false, hasWaterMat: true,
    lastCleaned: "Apr 16, 10:00am", lastCleanedBy: "Tyler", cleaningSignedOffBy: "Dave",
    lastOut: "N/A — new 2025", nextOut: "May 1, 2026 (season open)",
    morningCheckDone: false, morningCheckBy: "",
    outstandingTasks: ["Final pre-season detail Apr 28"],
    maintenanceNote: "Brand new 2025. Final pre-season setup underway.",
  },

  // ── DOCK B · RIGHT (shore → water) ───────────────────────────────────────
  {
    id: "sp1-kitts",
    name: "Kitts", code: "SP1",
    category: "Standard Pontoon",
    slip: 22, dock: "B", dockSide: "right", dockRow: 1,
    status: "in-service",
    hp: 115, capacity: 10, make: "Godfrey",
    notes: "Tritoon, single tube only, water mat. Older model, re-done interior.",
    canPullTube: true, canPullDouble: false, canPullKneeboard: false, hasWaterMat: true,
    lastCleaned: "Apr 19, 9:30am", lastCleanedBy: "Kenny", cleaningSignedOffBy: "Sam",
    lastOut: "Apr 19, 8:00am", nextOut: "Apr 20, 8:00am",
    morningCheckDone: true, morningCheckBy: "Kenny",
    outstandingTasks: [],
    maintenanceNote: "",
  },
  {
    id: "sp2-caicos",
    name: "Caicos", code: "SP2",
    category: "Standard Pontoon",
    slip: 23, dock: "B", dockSide: "right", dockRow: 2,
    status: "in-service",
    hp: 115, capacity: 10, make: "Bennington",
    notes: "Tritoon, single tube only, water mat.",
    canPullTube: true, canPullDouble: false, canPullKneeboard: false, hasWaterMat: true,
    lastCleaned: "Apr 19, 10:00am", lastCleanedBy: "Tyler", cleaningSignedOffBy: "Sam",
    lastOut: "Apr 19, 9:00am", nextOut: "Apr 20, 9:00am",
    morningCheckDone: true, morningCheckBy: "Tyler",
    outstandingTasks: [],
    maintenanceNote: "",
  },
  {
    id: "sp3-antigua",
    name: "Antigua", code: "SP3",
    category: "Standard Pontoon",
    slip: 24, dock: "B", dockSide: "right", dockRow: 3,
    status: "needs-maintenance",
    hp: 115, capacity: 10, make: "Bennington",
    notes: "Tritoon, single tube only.",
    canPullTube: true, canPullDouble: false, canPullKneeboard: false, hasWaterMat: true,
    lastCleaned: "Apr 18, 3:00pm", lastCleanedBy: "Zach", cleaningSignedOffBy: "Sam",
    lastOut: "Apr 18, 2:00pm", nextOut: "Apr 20, 10:00am",
    morningCheckDone: true, morningCheckBy: "Zach",
    outstandingTasks: [
      "Get a better photo of the tear — close up with the phone",
      "Measure the damage so Dave can quote the repair",
      "Ask Zach how it happened — figure out if it was guest damage",
      "Tell Dave before sending to service — he may be able to patch it",
    ],
    maintenanceNote: "Upholstery damage reported. Can still run — schedule repair this week.",
  },
  {
    id: "sp4-costa-rica",
    name: "Costa Rica", code: "SP4",
    category: "Standard Pontoon",
    slip: 25, dock: "B", dockSide: "right", dockRow: 4,
    status: "in-service",
    hp: 115, capacity: 10, make: "Bennington",
    notes: "Tritoon, single tube only.",
    canPullTube: true, canPullDouble: false, canPullKneeboard: false, hasWaterMat: true,
    lastCleaned: "Apr 19, 11:00am", lastCleanedBy: "Parker", cleaningSignedOffBy: "Sam",
    lastOut: "Apr 19, 10:00am", nextOut: "Apr 20, 10:00am",
    morningCheckDone: true, morningCheckBy: "Parker",
    outstandingTasks: [],
    maintenanceNote: "",
  },
  {
    id: "sp5-tortuga",
    name: "Tortuga", code: "SP5",
    category: "Standard Pontoon",
    slip: 26, dock: "B", dockSide: "right", dockRow: 5,
    status: "in-service",
    hp: 115, capacity: 10, make: "Bennington",
    notes: "Tritoon, single tube only.",
    canPullTube: true, canPullDouble: false, canPullKneeboard: false, hasWaterMat: true,
    lastCleaned: "Apr 19, 11:30am", lastCleanedBy: "Nate", cleaningSignedOffBy: "Dave",
    lastOut: "Apr 19, 11:00am", nextOut: "Apr 20, 11:00am",
    morningCheckDone: true, morningCheckBy: "Nate",
    outstandingTasks: [],
    maintenanceNote: "",
  },
  {
    id: "ep1-eppley",
    name: "Eppley", code: "EP1",
    category: "Economy Pontoon",
    slip: 27, dock: "B", dockSide: "right", dockRow: 6,
    status: "in-service",
    hp: 70, capacity: 8, make: "Bennington",
    notes: "NOT tritoon. Cannot pull tube. 70HP. Older model, updated interior.",
    canPullTube: false, canPullDouble: false, canPullKneeboard: false, hasWaterMat: true,
    lastCleaned: "Apr 19, 9:00am", lastCleanedBy: "Kenny", cleaningSignedOffBy: "Sam",
    lastOut: "Apr 19, 8:00am", nextOut: "Apr 20, 8:30am",
    morningCheckDone: true, morningCheckBy: "Kenny",
    outstandingTasks: [],
    maintenanceNote: "",
  },
  {
    id: "ep2-martinique",
    name: "Martinique", code: "EP2",
    category: "Economy Pontoon",
    slip: 28, dock: "B", dockSide: "right", dockRow: 7,
    status: "in-service",
    hp: 115, capacity: 8, make: "Bennington",
    notes: "NOT tritoon. 115HP (not advertised). Older model, updated interior.",
    canPullTube: false, canPullDouble: false, canPullKneeboard: false, hasWaterMat: true,
    lastCleaned: "Apr 19, 9:30am", lastCleanedBy: "Zach", cleaningSignedOffBy: "Sam",
    lastOut: "Apr 19, 9:00am", nextOut: "Apr 20, 9:00am",
    morningCheckDone: true, morningCheckBy: "Zach",
    outstandingTasks: [],
    maintenanceNote: "",
  },
  {
    id: "sr1-atlantique",
    name: "Atlantique", code: "SR1",
    category: "Standard Runabout",
    slip: 29, dock: "B", dockSide: "right", dockRow: 8,
    status: "in-service",
    hp: 150, capacity: 8, make: "Four Winns",
    notes: "Open bow runabout. Single tube, double, kneeboard.",
    canPullTube: true, canPullDouble: true, canPullKneeboard: true, hasWaterMat: false,
    lastCleaned: "Apr 19, 10:00am", lastCleanedBy: "Tyler", cleaningSignedOffBy: "Sam",
    lastOut: "Apr 19, 10:00am", nextOut: "Apr 20, 10:00am",
    morningCheckDone: true, morningCheckBy: "Tyler",
    outstandingTasks: [],
    maintenanceNote: "",
  },
  {
    id: "sr2-montauk",
    name: "Montauk", code: "SR2",
    category: "Standard Runabout",
    slip: 30, dock: "B", dockSide: "right", dockRow: 9,
    status: "in-service",
    hp: 150, capacity: 8, make: "Four Winns",
    notes: "Open bow runabout.",
    canPullTube: true, canPullDouble: true, canPullKneeboard: true, hasWaterMat: false,
    lastCleaned: "Apr 19, 10:30am", lastCleanedBy: "Parker", cleaningSignedOffBy: "Sam",
    lastOut: "Apr 19, 11:00am", nextOut: "Apr 20, 11:00am",
    morningCheckDone: true, morningCheckBy: "Parker",
    outstandingTasks: [],
    maintenanceNote: "",
  },
  {
    id: "sr3-gilgo",
    name: "Gilgo", code: "SR3",
    category: "Standard Runabout",
    slip: 31, dock: "B", dockSide: "right", dockRow: 10,
    status: "out-of-service",
    hp: 150, capacity: 8, make: "Four Winns",
    notes: "Open bow runabout.",
    canPullTube: true, canPullDouble: true, canPullKneeboard: true, hasWaterMat: false,
    lastCleaned: "Apr 16, 4:00pm", lastCleanedBy: "Nate", cleaningSignedOffBy: "Dave",
    lastOut: "Apr 16, 3:00pm", nextOut: "TBD",
    morningCheckDone: false, morningCheckBy: "",
    outstandingTasks: [
      "Confirm return date with Matt — expected Apr 23",
      "Tell Dave the boat is coming back before the weekend",
    ],
    maintenanceNote: "Scheduled engine service. Estimated back Apr 23.",
  },
  {
    id: "sr4-dunewood",
    name: "Dunewood", code: "SR4",
    category: "Standard Runabout",
    slip: 32, dock: "B", dockSide: "right", dockRow: 11,
    status: "in-service",
    hp: 150, capacity: 8, make: "Four Winns",
    notes: "Open bow runabout.",
    canPullTube: true, canPullDouble: true, canPullKneeboard: true, hasWaterMat: false,
    lastCleaned: "Apr 19, 11:00am", lastCleanedBy: "Kenny", cleaningSignedOffBy: "Sam",
    lastOut: "Apr 19, 12:00pm", nextOut: "Apr 20, 12:00pm",
    morningCheckDone: true, morningCheckBy: "Kenny",
    outstandingTasks: [],
    maintenanceNote: "",
  },
  {
    id: "cayman",
    name: "Cayman", code: "",
    category: "Charter Vessel",
    slip: 34, dock: "B", dockSide: "right", dockRow: 13,
    status: "in-service",
    hp: 115, capacity: 10, make: "Pontoon",
    notes: "Charter vessel.",
    canPullTube: false, canPullDouble: false, canPullKneeboard: false, hasWaterMat: false,
    lastCleaned: "Apr 19, 8:30am", lastCleanedBy: "Tyler", cleaningSignedOffBy: "Dave",
    lastOut: "Apr 19, 4:00pm", nextOut: "Apr 20, 2:00pm",
    morningCheckDone: true, morningCheckBy: "Tyler",
    outstandingTasks: [],
    maintenanceNote: "",
  },
  {
    id: "aruba",
    name: "Aruba", code: "",
    category: "Charter Vessel",
    slip: 35, dock: "B", dockSide: "right", dockRow: 14,
    status: "in-service",
    hp: 115, capacity: 10, make: "Pontoon",
    notes: "Charter vessel.",
    canPullTube: false, canPullDouble: false, canPullKneeboard: false, hasWaterMat: false,
    lastCleaned: "Apr 19, 8:30am", lastCleanedBy: "Nate", cleaningSignedOffBy: "Dave",
    lastOut: "Apr 19, 3:00pm", nextOut: "Apr 20, 3:00pm",
    morningCheckDone: true, morningCheckBy: "Nate",
    outstandingTasks: [],
    maintenanceNote: "",
  },
  {
    id: "caribbean",
    name: "Caribbean", code: "",
    category: "Charter Vessel",
    slip: 36, dock: "B", dockSide: "right", dockRow: 15,
    status: "in-service",
    hp: 115, capacity: 12, make: "Pontoon",
    notes: "Charter vessel.",
    canPullTube: false, canPullDouble: false, canPullKneeboard: false, hasWaterMat: false,
    lastCleaned: "Apr 19, 9:00am", lastCleanedBy: "Parker", cleaningSignedOffBy: "Dave",
    lastOut: "Apr 19, 5:00pm", nextOut: "Apr 20, 1:00pm",
    morningCheckDone: true, morningCheckBy: "Parker",
    outstandingTasks: [],
    maintenanceNote: "",
  },
];

export const statusConfig = {
  "in-service": {
    label: "In Service",
    bg: "#d1fae5",
    border: "#6ee7b7",
    text: "#064e3b",
    dot: "#10b981",
  },
  "needs-maintenance": {
    label: "Needs Maintenance",
    bg: "#fef3c7",
    border: "#fcd34d",
    text: "#78350f",
    dot: "#f59e0b",
  },
  "out-of-service": {
    label: "Out of Service",
    bg: "#fee2e2",
    border: "#fca5a5",
    text: "#7f1d1d",
    dot: "#ef4444",
  },
  "dry-dock": {
    label: "Dry Dock",
    bg: "#f1f5f9",
    border: "#cbd5e1",
    text: "#475569",
    dot: "#94a3b8",
  },
};
